function mapsQuery(q: string) {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
}

export const SITE = {
  name: "啟揚機電",
  legalName: "啟揚機電有限公司",
  phoneDisplay: "07-353-8504",
  phoneTel: "+88673538504",
  faxDisplay: "07-353-5947",
  freePhoneDisplay: "0800-000-362",
  freePhoneTel: "0800000362",
  email: "chi.yang7039@gmail.com",
  address: "高雄市大社區民族路15-10號",
  mapsUrl: mapsQuery("高雄市大社區民族路15-10號"),
  formUrl: "https://forms.gle/uCqMDaTfuiHCuHvw8",
  formEmbed:
    "https://docs.google.com/forms/d/e/1FAIpQLSc_x3GjKPbV5HJPzPIkE6RjVgxlVF9yDOQAufMpg62_97D3uQ/viewform",
  formSourceEntry: "1632618831",
  facebook: "https://www.facebook.com/profile.php?id=100064054864315",
  instagram: "https://www.instagram.com/chiyang.elevator/",
  reel: "https://www.facebook.com/reel/1033082013055204",
  line: "",
} as const;

export const LEAD_SOURCES = [
  { id: "site", label: "官方網站", value: "啟揚官方網站" },
  { id: "fb", label: "臉書", value: "Facebook 粉專" },
  { id: "ig", label: "Instagram", value: "其他" },
  { id: "google", label: "Google", value: "Google 搜尋" },
  { id: "friend", label: "親友介紹", value: "親友或合作夥伴介紹" },
] as const;

export function formWithSource(sourceValue: string) {
  const u = new URL(SITE.formEmbed);
  u.searchParams.set("usp", "pp_url");
  u.searchParams.set(`entry.${SITE.formSourceEntry}`, sourceValue);
  u.searchParams.set("embedded", "true");
  return u.toString();
}

export const LOCATIONS = [
  {
    id: "kh",
    name: "高雄總公司",
    address: "高雄市大社區民族路15-10號",
    phoneDisplay: "07-353-8504",
    phoneTel: "+88673538504",
    faxDisplay: "07-353-5947",
    mapsUrl: mapsQuery("高雄市大社區民族路15-10號"),
  },
  {
    id: "tn",
    name: "台南展銷中心",
    address: "台南市永康區中山北路343號",
    phoneDisplay: "06-231-3662",
    phoneTel: "+88662313662",
    faxDisplay: "06-231-9772",
    mapsUrl: mapsQuery("台南市永康區中山北路343號"),
  },
  {
    id: "tc",
    name: "台中清水展銷中心",
    address: "台中市清水區民族路三段63號1樓",
    phoneDisplay: "",
    phoneTel: "",
    faxDisplay: "",
    mapsUrl: mapsQuery("台中市清水區民族路三段63號1樓"),
  },
  {
    id: "ty",
    name: "桃園展銷中心",
    address: "桃園市八德區仁德一路138號",
    phoneDisplay: "",
    phoneTel: "",
    faxDisplay: "",
    mapsUrl: mapsQuery("桃園市八德區仁德一路138號"),
  },
] as const;

export const SLOGANS = {
  install: { line1: "電梯不好裝，", line2: "啟揚就來裝。" },
  maintain: { line1: "電梯不好養，", line2: "啟揚就來養。" },
  floor: { line1: "地板不能挖，", line2: "啟揚有辦法。" },
} as const;

export const STORY = {
  kicker: "為什麼找啟揚",
  title: "別家說裝不了的家，我們來看現場。",
  body: "這不是樣品屋。是已經住進去的透天：樓梯窄、位置怪、地板不能大挖。先看這個家怎麼住，能裝才說怎麼裝。裝完，保養也找我們。",
} as const;

export const ABOUT = {
  kicker: "啟揚怎麼來的",
  title: "先會裝，才開了這家公司。",
  lead: "峰哥喜歡裝電梯。為了幫更多已經住進去的家，2016 年成立啟揚。自己看現場、自己裝。",
  stages: [
    {
      n: "01",
      title: "峰哥先裝",
      body: "從現場出來的。難裝、位置怪、別家不接的，他先看。",
    },
    {
      n: "02",
      title: "業務與工務成形",
      body: "人多了，黃大姐把客人接進來；田大哥帶工務把現場做完。不是一個人扛全場。",
    },
    {
      n: "03",
      title: "專心做客製化的家",
      body: "舊透天、有限空間、裝完也養。目標是把這條路走穩，不跟大廠搶大樓標案。",
    },
  ],
} as const;

export const PEOPLE = [
  {
    id: "feng",
    name: "峰哥",
    role: "創辦人",
    bio: "現場出來的。喜歡把電梯裝進已經住著的家。",
    image: "/images/team/IMG_3584.webp",
  },
  {
    id: "huang",
    name: "黃大姐",
    role: "業務",
    bio: "客人怎麼問、現場怎麼接，她把這條線接起來。",
    image: "",
  },
  {
    id: "tian",
    name: "田大哥",
    role: "工務",
    bio: "能不能裝、怎麼裝完，工務看現場。",
    image: "",
  },
] as const;

export const TEAM_PHOTOS = [
  { src: "/images/team/IMG_3556.webp", alt: "啟揚團隊" },
  { src: "/images/team/IMG_3557.webp", alt: "啟揚團隊合影" },
  { src: "/images/team/IMG_3579.webp", alt: "開會" },
] as const;

export const SURVEY = [
  "幾樓到幾樓",
  "梯放樓梯中間、旁邊，還是室外",
  "一次幾個人，要不要坐輪椅或載貨",
  "門要開哪一邊，能不能雙向",
  "地板、防水能不能動，能動多少",
] as const;

export const PAINS = [
  {
    id: "narrow",
    title: "空間太窄",
    body: "樓梯旁、畸零地、沒有現成井道。別家說塞不進去的，先拍照給我們看。",
  },
  {
    id: "floor",
    title: "地板不能挖",
    body: "怕動到防水、管線、地基。有的現場能少動地板，做法以現勘為準。",
  },
  {
    id: "refused",
    title: "別家不接",
    body: "案子小、位置難、結構不好拆。我們專門看這類已經住進去的家。",
  },
  {
    id: "elders",
    title: "長輩爬樓",
    body: "膝蓋、輪椅、日常上下樓。先說家人怎麼住，再談電梯怎麼放。",
  },
] as const;

export const STEPS = [
  { n: "01", title: "拍照傳圖", body: "樓梯、預計位置、各樓層出入口。沒有尺寸也可以先傳。" },
  { n: "02", title: "說明能不能裝", body: "先講生活需求與現場限制，能做、不能做、下一步怎麼走。" },
  { n: "03", title: "到府現勘", body: "結構、動線、出入口與施工界面，以現場為準。" },
  { n: "04", title: "圖說與合約", body: "規格、範圍、保養怎麼接，寫進文件再進場。" },
] as const;

export const FAQS = [
  {
    id: "installable",
    q: "我家到底能不能裝？",
    a: "不能只看屋齡或一張照片。先確認房屋類型、樓層、預定位置、結構與出入口，再整理可行方向。",
  },
  {
    id: "space",
    q: "空間夠不夠？",
    a: "寬深以外，梁柱、樓板、管線、門向和施工通道都會影響。照片可先談，正式判斷仍要現勘。",
  },
  {
    id: "pit",
    q: "一定要大挖地板嗎？",
    a: "不一定。有的現場能少動地板，用較淺的做法或墊高。深度與做法以現勘、圖說和合約為準，網站不寫死規格。",
  },
  {
    id: "sequence",
    q: "裝修跟電梯誰先？",
    a: "若正在翻修，提早把電梯放進整體規劃，先對齊井道、出入口與裝修界面，再決定施工順序。",
  },
  {
    id: "prepare",
    q: "詢問前要準備什麼？",
    a: "縣市、房屋類型、樓層、想裝的位置，以及樓梯周邊照片。沒有完整尺寸也能先說明需求。",
  },
  {
    id: "maintenance",
    q: "裝完之後誰養？",
    a: "新梯與保養是兩件事，我們都接。依設備現況與正式服務內容確認，可先說目前的問題。",
  },
] as const;

export const CATALOG = [
  { id: "CAT-01", title: "主機系統", image: "/images/catalog/cat-01.webp" },
  { id: "CAT-02", title: "主機系統", image: "/images/catalog/cat-02.webp" },
  { id: "CAT-03", title: "變頻門機", image: "/images/catalog/cat-03.webp" },
  { id: "CAT-04", title: "門機與光幕", image: "/images/catalog/cat-04.webp" },
  { id: "CAT-05", title: "車廂裝潢", image: "/images/catalog/cat-05.webp" },
  { id: "CAT-06", title: "車廂裝潢", image: "/images/catalog/cat-06.webp" },
  { id: "CAT-07", title: "轎廂天花", image: "/images/catalog/cat-07.webp" },
  { id: "CAT-08", title: "轎廂天花", image: "/images/catalog/cat-08.webp" },
  { id: "CAT-09", title: "型錄", image: "/images/catalog/cat-09.webp" },
  { id: "CAT-10", title: "型錄", image: "/images/catalog/cat-10.webp" },
  { id: "CAT-11", title: "型錄", image: "/images/catalog/cat-11.webp" },
  { id: "CAT-12", title: "型錄", image: "/images/catalog/cat-12.webp" },
  { id: "CAT-13", title: "車廂", image: "/images/catalog/cat-13.webp" },
  { id: "CAT-14", title: "車廂", image: "/images/catalog/cat-14.webp" },
  { id: "CAT-15", title: "車廂", image: "/images/catalog/cat-15.webp" },
  { id: "CAT-16", title: "車廂", image: "/images/catalog/cat-16.webp" },
  { id: "CAT-17", title: "車廂", image: "/images/catalog/cat-17.webp" },
  { id: "CAT-18", title: "車廂", image: "/images/catalog/cat-18.webp" },
  { id: "CAT-19", title: "門套", image: "/images/catalog/cat-19.webp" },
  { id: "CAT-20", title: "門套", image: "/images/catalog/cat-20.webp" },
  { id: "CAT-21", title: "門套", image: "/images/catalog/cat-21.webp" },
  { id: "CAT-22", title: "按鈕", image: "/images/catalog/cat-22.webp" },
  { id: "CAT-23", title: "操作盤", image: "/images/catalog/cat-23.webp" },
  { id: "CAT-24", title: "門機", image: "/images/catalog/cat-24.webp" },
  { id: "CAT-25", title: "門機", image: "/images/catalog/cat-25.webp" },
  { id: "CAT-26", title: "門機", image: "/images/catalog/cat-26.webp" },
] as const;

export type CaseItem = {
  id: string;
  area: string;
  title: string;
  stage: string;
  image: string;
  note: string;
};

export const MAINTAIN = [
  { title: "保養", body: "定期保養，讓設備可以長期運作。" },
  { title: "點檢", body: "機件連動、電路測試、主吊鋼索點檢。" },
  { title: "潤滑", body: "開門機清理上油、添加導軌油。" },
  { title: "清潔", body: "機房、升降路、控制盤與主機清潔。" },
  { title: "調整", body: "停車水平、開關門異音調整。" },
  { title: "更換", body: "消耗品與零件更換先報價再做。" },
] as const;

export const CASES: CaseItem[] = [
  {
    id: "QY-750",
    area: "高雄三民",
    title: "高雄三民-P6景觀家用梯(雙出口)",
    stage: "工程實績",
    image: "/images/works/qy-750.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-720",
    area: "台南東區",
    title: "台南東區-P3電梯(手掀門式)",
    stage: "工程實績",
    image: "/images/works/qy-720.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-770",
    area: "高雄楠梓",
    title: "高雄楠梓-P8客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-770.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-730",
    area: "台南南區",
    title: "台南南區-P3家用梯",
    stage: "工程實績",
    image: "/images/works/qy-730.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-740",
    area: "桃園龜山",
    title: "桃園龜山-P5家用梯",
    stage: "工程實績",
    image: "/images/works/qy-740.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-760",
    area: "新竹",
    title: "新竹-P5家用梯",
    stage: "工程實績",
    image: "/images/works/qy-760.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-715",
    area: "高雄梓官",
    title: "高雄梓官-P5家用梯",
    stage: "工程實績",
    image: "/images/works/qy-715.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-709",
    area: "台南新化",
    title: "台南新化-P6(藝術玻璃樣式)",
    stage: "工程實績",
    image: "/images/works/qy-709.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-699",
    area: "高雄燕巢",
    title: "高雄燕巢-貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-699.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-689",
    area: "高雄鳳山",
    title: "高雄鳳山-P6客梯",
    stage: "工程實績",
    image: "/images/works/qy-689.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-679",
    area: "台南北區",
    title: "台南北區-P3家用梯",
    stage: "工程實績",
    image: "/images/works/qy-679.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-549",
    area: "台南東區",
    title: "台南東區-P5(藝術玻璃樣式)",
    stage: "工程實績",
    image: "/images/works/qy-549.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-591",
    area: "台南安平",
    title: "台南安平-P6",
    stage: "工程實績",
    image: "/images/works/qy-591.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-615",
    area: "高雄旗山",
    title: "高雄旗山-P10客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-615.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-567",
    area: "高雄鳳山",
    title: "高雄鳳山-P5(藝術玻璃樣式)",
    stage: "工程實績",
    image: "/images/works/qy-567.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-651",
    area: "新竹",
    title: "新竹-P6景觀家用梯(透視窗)",
    stage: "工程實績",
    image: "/images/works/qy-651.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-555",
    area: "高雄仁武",
    title: "高雄仁武-P6(藝術玻璃樣式)",
    stage: "工程實績",
    image: "/images/works/qy-555.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-639",
    area: "高雄小港",
    title: "高雄小港-P6電梯",
    stage: "工程實績",
    image: "/images/works/qy-639.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-627",
    area: "雲林虎尾",
    title: "雲林虎尾-P6電梯",
    stage: "工程實績",
    image: "/images/works/qy-627.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-579",
    area: "高雄林園",
    title: "高雄林園-P6客梯(透視窗)",
    stage: "工程實績",
    image: "/images/works/qy-579.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-603",
    area: "桃園",
    title: "桃園-小型送菜梯",
    stage: "工程實績",
    image: "/images/works/qy-603.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-663",
    area: "高雄楠梓",
    title: "高雄楠梓-P6(藝術玻璃樣式)",
    stage: "工程實績",
    image: "/images/works/qy-663.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-675",
    area: "台北內湖",
    title: "台北內湖-P6(90度雙出口)",
    stage: "工程實績",
    image: "/images/works/qy-675.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-543",
    area: "新竹",
    title: "新竹-P6景觀梯",
    stage: "工程實績",
    image: "/images/works/qy-543.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-531",
    area: "雲林虎尾",
    title: "雲林虎尾-P6電梯",
    stage: "工程實績",
    image: "/images/works/qy-531.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-480",
    area: "臺南大學",
    title: "臺南大學-P6客制化無障礙電梯",
    stage: "工程實績",
    image: "/images/works/qy-480.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-504",
    area: "高雄苓雅",
    title: "高雄苓雅-貨梯工程(1F前後雙出口)",
    stage: "工程實績",
    image: "/images/works/qy-504.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-468",
    area: "台北內湖",
    title: "台北內湖-P5電梯(前後雙出口)",
    stage: "工程實績",
    image: "/images/works/qy-468.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-492",
    area: "高雄鳥松",
    title: "高雄鳥松-P6客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-492.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-516",
    area: "高雄岡山",
    title: "高雄岡山-貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-516.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-444",
    area: "高雄路竹",
    title: "高雄路竹-P6客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-444.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-441",
    area: "高雄大寮",
    title: "高雄大寮-P6電梯(藝術玻璃樣式)",
    stage: "工程實績",
    image: "/images/works/qy-441.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-437",
    area: "嘉義東區",
    title: "嘉義東區-P6客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-437.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-456",
    area: "高雄仁武",
    title: "高雄仁武-P6電梯",
    stage: "工程實績",
    image: "/images/works/qy-456.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-528",
    area: "高雄三民區",
    title: "高雄三民區-P12無障礙電梯工程",
    stage: "工程實績",
    image: "/images/works/qy-528.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-428",
    area: "台南中西區",
    title: "台南中西區-P5客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-428.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-408",
    area: "地區匿名",
    title: "高雄左營貨梯(隨貨一人)工程",
    stage: "工程實績",
    image: "/images/works/qy-408.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-432",
    area: "桃園龍潭",
    title: "桃園龍潭-四噸貨梯工程(不锈鋼樣式)",
    stage: "工程實績",
    image: "/images/works/qy-432.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-354",
    area: "地區匿名",
    title: "台南北區P5客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-354.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-387",
    area: "地區匿名",
    title: "高雄楠梓P8客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-387.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-395",
    area: "高雄鼓山",
    title: "高雄鼓山-P6電梯(藝術玻璃樣式)",
    stage: "工程實績",
    image: "/images/works/qy-395.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-370",
    area: "地區匿名",
    title: "高雄鳳山P5客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-370.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-383",
    area: "地區匿名",
    title: "台南永康1500KG貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-383.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-398",
    area: "地區匿名",
    title: "台東達仁P10客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-398.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-403",
    area: "地區匿名",
    title: "嘉義鹿草P8無障礙客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-403.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-362",
    area: "地區匿名",
    title: "高雄前金P6客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-362.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-418",
    area: "地區匿名",
    title: "屏東P6客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-418.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-378",
    area: "地區匿名",
    title: "屏東潮州小型送貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-378.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-352",
    area: "公司",
    title: "公司-展示梯",
    stage: "工程實績",
    image: "/images/works/qy-352.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-344",
    area: "地區匿名",
    title: "楠梓藍昌P8客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-344.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-339",
    area: "地區匿名",
    title: "台南安南新設90度貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-339.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-336",
    area: "地區匿名",
    title: "鳳山吳公館新設P6客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-336.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-333",
    area: "地區匿名",
    title: "路竹陳公館P6新設客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-333.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-327",
    area: "地區匿名",
    title: "台南安南新設貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-327.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-321",
    area: "地區匿名",
    title: "橋頭新設客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-321.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-315",
    area: "地區匿名",
    title: "高師大校園無障礙客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-315.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-309",
    area: "地區匿名",
    title: "東港陳公館新設客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-309.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-303",
    area: "地區匿名",
    title: "苗栗新設客貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-303.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-297",
    area: "地區匿名",
    title: "鳥松P5新設客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-297.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-291",
    area: "地區匿名",
    title: "左營貨梯整修工程",
    stage: "工程實績",
    image: "/images/works/qy-291.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-285",
    area: "地區匿名",
    title: "燕巢貨梯整修工程",
    stage: "工程實績",
    image: "/images/works/qy-285.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-279",
    area: "地區匿名",
    title: "旗津新設貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-279.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-267",
    area: "地區匿名",
    title: "台南水電行電梯鋼構工程",
    stage: "工程實績",
    image: "/images/works/qy-267.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-261",
    area: "地區匿名",
    title: "岡山廖公館P6新設客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-261.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-255",
    area: "地區匿名",
    title: "新北市無塵室新設小型送貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-255.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-243",
    area: "地區匿名",
    title: "台南永康住家P5新設客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-243.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-237",
    area: "地區匿名",
    title: "楠梓新設菜梯工程",
    stage: "工程實績",
    image: "/images/works/qy-237.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-231",
    area: "地區匿名",
    title: "鳥松新設貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-231.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-225",
    area: "地區匿名",
    title: "左營藝術中心P15無障礙客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-225.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-219",
    area: "地區匿名",
    title: "岡山科技公司90度開口新設貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-219.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-213",
    area: "地區匿名",
    title: "新北市新設小型送貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-213.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-207",
    area: "地區匿名",
    title: "鳳山科技公司P6客梯",
    stage: "工程實績",
    image: "/images/works/qy-207.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-201",
    area: "地區匿名",
    title: "楠梓P6客梯工程",
    stage: "工程實績",
    image: "/images/works/qy-201.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-195",
    area: "地區匿名",
    title: "台中梧棲新設貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-195.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-189",
    area: "地區匿名",
    title: "台南電梯鋼構工程",
    stage: "工程實績",
    image: "/images/works/qy-189.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-183",
    area: "地區匿名",
    title: "里港新設貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-183.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-177",
    area: "地區匿名",
    title: "左營車廂裝潢工程",
    stage: "工程實績",
    image: "/images/works/qy-177.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-171",
    area: "地區匿名",
    title: "小型送貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-171.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-165",
    area: "地區匿名",
    title: "鹽塩舊大樓整修工程",
    stage: "工程實績",
    image: "/images/works/qy-165.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-159",
    area: "地區匿名",
    title: "台南安定貨梯工程",
    stage: "工程實績",
    image: "/images/works/qy-159.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
  {
    id: "QY-153",
    area: "地區匿名",
    title: "台南手拉門更新工程",
    stage: "工程實績",
    image: "/images/works/qy-153.webp",
    note: "舊站工程實績。只描述畫面看得見的。",
  },
];
